const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('piedPiper', {
  listEncyclopediaTopics: () => ipcRenderer.invoke('encyclopedia:list-topics'),
  createEncyclopediaTopic: (payload) => ipcRenderer.invoke('encyclopedia:create-topic', payload),
  updateEncyclopediaTopic: (id, payload) => ipcRenderer.invoke('encyclopedia:update-topic', id, payload),
  deleteEncyclopediaTopic: (id) => ipcRenderer.invoke('encyclopedia:delete-topic', id),
  getEncyclopediaTopic: (id) => ipcRenderer.invoke('encyclopedia:get-topic', id),
  listEncyclopediaLinks: (topicId) => ipcRenderer.invoke('encyclopedia:list-links', topicId),
  createEncyclopediaLink: (topicId, payload) =>
    ipcRenderer.invoke('encyclopedia:create-link', topicId, payload),
  updateEncyclopediaLink: (id, payload) => ipcRenderer.invoke('encyclopedia:update-link', id, payload),
  deleteEncyclopediaLink: (id) => ipcRenderer.invoke('encyclopedia:delete-link', id),
  openEncyclopediaLink: (url) => ipcRenderer.invoke('encyclopedia:open-link', url),
  uploadEncyclopediaPdf: (topicId) => ipcRenderer.invoke('encyclopedia:upload-pdf', topicId),
  listEncyclopediaPdfs: (topicId) => ipcRenderer.invoke('encyclopedia:list-pdfs', topicId),
  deleteEncyclopediaPdf: (id) => ipcRenderer.invoke('encyclopedia:delete-pdf', id),
  readEncyclopediaPdfData: (filePath) => ipcRenderer.invoke('encyclopedia:read-pdf-data', filePath),
  openEncyclopediaPdfExternal: (filePath) => ipcRenderer.invoke('encyclopedia:open-pdf-external', filePath),
  getTodoState: () => ipcRenderer.invoke('todo:get-state'),
  createTodoList: (payload) => ipcRenderer.invoke('todo:create-list', payload),
  addTodoTask: (payload) => ipcRenderer.invoke('todo:add-task', payload),
  setTodoTaskCompleted: (id, isCompleted) =>
    ipcRenderer.invoke('todo:set-task-completed', id, isCompleted),
  deleteTodoList: () => ipcRenderer.invoke('todo:delete-list'),
  listNotebooks: (params) => ipcRenderer.invoke('notes:list', params),
  getNotebook: (id) => ipcRenderer.invoke('notes:get', id),
  createNotebook: (title) => ipcRenderer.invoke('notes:create', title),
  discardEmptyNotebook: (id) => ipcRenderer.invoke('notes:discard-empty', id),
  saveNotebook: (payload) => ipcRenderer.invoke('notes:save', payload),
  softDeleteNotebook: (id) => ipcRenderer.invoke('notes:soft-delete', id),
  restoreNotebook: (id) => ipcRenderer.invoke('notes:restore', id),
  permanentlyDeleteNotebook: (id) => ipcRenderer.invoke('notes:permanent-delete', id),
  listNotebookTags: () => ipcRenderer.invoke('notes:list-tags'),
  renameNotebookTag: (oldTag, newTag) => ipcRenderer.invoke('notes:rename-tag', oldTag, newTag),
  storeNotebookImage: (filename, dataBase64) =>
    ipcRenderer.invoke('notes:store-image', filename, dataBase64),
  openNotebookLink: (url) => ipcRenderer.invoke('notes:open-link', url),
  exportNotebookPdf: (payload) => ipcRenderer.invoke('notes:export-pdf', payload),
  listHelpbook: () => ipcRenderer.invoke('helpbook:list'),
  createHelpbook: (payload) => ipcRenderer.invoke('helpbook:create', payload),
  updateHelpbook: (id, payload) => ipcRenderer.invoke('helpbook:update', id, payload),
  deleteHelpbook: (id) => ipcRenderer.invoke('helpbook:delete', id),
  listPrompts: () => ipcRenderer.invoke('prompts:list'),
  createPrompt: (payload) => ipcRenderer.invoke('prompts:create', payload),
  updatePrompt: (id, payload) => ipcRenderer.invoke('prompts:update', id, payload),
  deletePrompt: (id) => ipcRenderer.invoke('prompts:delete', id),
  listRecycleBinCategories: () => ipcRenderer.invoke('recycle-bin:list-categories'),
  listRecycleBinItems: (category) => ipcRenderer.invoke('recycle-bin:list-items', category),
  restoreRecycleBinItems: (recycleItemIds) =>
    ipcRenderer.invoke('recycle-bin:restore-items', recycleItemIds),
  permanentlyDeleteRecycleBinItems: (recycleItemIds) =>
    ipcRenderer.invoke('recycle-bin:permanently-delete-items', recycleItemIds),
  getApplicationSettings: () => ipcRenderer.invoke('settings:get'),
  saveApplicationSettings: (payload) => ipcRenderer.invoke('settings:save', payload),
  exportDatabase: () => ipcRenderer.invoke('settings:export-database'),
  importDatabase: () => ipcRenderer.invoke('settings:import-database'),
  createDatabaseBackup: () => ipcRenderer.invoke('settings:create-backup'),
})
